name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Lint with flake8
        run: ./lint.sh

      - name: Run tests with coverage
        env:
          PYTHONPATH: rest_api
        run: |
          pytest --cov=app --cov-report=term-missing

      - name: Build Docker image
        run: docker build -t my-fastapi-app .